# TODO(jlewi): Should we produce this from a jinja template so we can easily rewrite the image when we build a new
# image?
apiVersion: "mlkube.io/v1beta1"
kind: "TfJob"
metadata:
  name: "example-job"
spec:
  replicaSpecs:
    - replicas: 1
      tfPort: 2222
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:81f3e2e-dirty-9519887
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 1
      tfPort: 2222
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:81f3e2e-dirty-9519887
              name: tensorflow
          restartPolicy: OnFailure